import math
import os
import random
import time

import pybullet as p
import pybullet_data as pd

#-------- basic settings ------
p.connect(p.GUI)
p.setAdditionalSearchPath(pd.getDataPath())

#-------- additional settings ------
texture_id = -1                         # initialize textureId with invalid value
use_programmatic = 0                    # A constant indicating that terrain is generated programmatically
use_terrain_from_png = 1                # A constant indicating that terrain is generated by png file.
use_deep_loco_csv = 2                   # A constant indicating that terrain is generated by csv file.
update_heightfield = False              # A variable indicating whether terrain need to be update.
heigfield_source = use_programmatic     # Set the method for generating terrain by program.

random.seed(10)                         # Set the seed of random number.
p.configureDebugVisualizer(p.COV_ENABLE_RENDERING, 0)   # Disable the debug visualizer
height_perturbation_range = 0.05

